//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Campaigns = new HashSet<Campaign>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
    }
}
