//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Report
    {
        public int id { get; set; }
        public int campaign_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<int> device_id { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual User User { get; set; }
        public virtual Device Device { get; set; }
    }
}
